name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  get-changed-dir:
    name: get-changed-dir
    runs-on: ubuntu-24.04
    outputs:
      changed-dir: ${{ steps.get-changed-dir.outputs.changed-dir }}
      dir-count: ${{ steps.dir-count.outputs.dir-count }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch remote branches
        run: >-
          git fetch --no-tags --prune --depth=1 origin
          +refs/heads/*:refs/remotes/origin/*

      - name: Get changed directories
        run: |
          git diff --name-only origin/"$BASE_REF" "$SHA" | awk -F/ '{print $1}' | sort -u | xargs > changed-dirs.txt
          echo "Changed directories: \"$(cat changed-dirs.txt)\""
        env:
          BASE_REF: ${{ github.base_ref }}
          SHA: ${{ github.event.pull_request.head.sha }}

      - name: Count number of modified directories
        id: dir-count
        run: |
          DIR_COUNT="$(wc -l changed-dirs.txt | awk '{print $1}')"
          echo "Number of changed directories: \"$DIR_COUNT\""
          echo "dir-count=$DIR_COUNT" >> "$GITHUB_OUTPUT"

      - name: Check if only one dir from the monorepo was modified, except .github and root
        run: |
          import os
          import sys

          def check_files(changed_dirs):
            projects = ['app']

            with open(changed_dirs, 'r') as cd:
              dirs = cd.read().splitlines()

            print(os.environ['DIR_COUNT'])
            if any(project in dirs for project in projects):
              if os.environ['DIR_COUNT'] != '1':
                sys.exit(1)

          check_files('changed-dirs.txt')
        shell: python
        env:
          DIR_COUNT: ${{ steps.dir-count.outputs.dir-count }}

      - name: Create output for changed directories
        id: get-changed-dir
        if: steps.dir-count.outputs.dir-count == '1'
        run: |
          echo "changed-dir=$(cat changed-dirs.txt)" >> "$GITHUB_OUTPUT"
          rm -f changed-dirs.txt

  pre-commit:
    name: pre-commit
    needs: get-changed-dir
    permissions:
      contents: write
    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          version: "0.8.15"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install pre-commit
        run: uv tool install pre-commit

      - name: Cache pre-commit dependencies
        id: cache_pre_commit
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
        env:
          CACHE-NAME: cache-pre-commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ env.CACHE-NAME }}-${{ hashFiles('.pre-commit-config.yaml', '~/.cache/pre-commit/*') }}

      - name: Install pre-commit hooks
        if: steps.cache_pre_commit.outputs.cache-hit != 'true'
        run: |
          pre-commit install
          pre-commit gc

      # Only install if the directory is 'app', as it is the only directory expected to have a Dockerfile
      - name: Install hadolint
        if:
          needs.get-changed-dir.outputs.dir-count == '1' &&
          needs.get-changed-dir.outputs.changed-dir == 'app'
        run: >-
          curl -L "$(
          curl -s https://api.github.com/repos/hadolint/hadolint/releases/latest
          | grep -o -E -i -m 1 "https://.+?/hadolint-linux-x86_64"
          )"
          > hadolint
          && chmod +x hadolint && sudo mv hadolint /usr/bin/

      - name: Run pre-commit hooks
        run: >-
          pre-commit run
          --from-ref origin/"$BASE_REF"
          --to-ref "$SHA"
          --color=always
          --show-diff-on-failure
        env:
          BASE_REF: ${{ github.base_ref }}
          SHA: ${{ github.event.pull_request.head.sha }}

  app:
    name: app
    needs:
      - get-changed-dir
      - pre-commit
    if:
      needs.get-changed-dir.outputs.dir-count == '1' &&
      needs.get-changed-dir.outputs.changed-dir == 'app'
    uses: ./.github/workflows/app-on-pr.yml
    permissions:
      contents: read
      actions: read
      packages: write
      security-events: write
